matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: node_js
    node_js: '9'
  # - os: linux
  #   services: docker
  #   language: generic

sudo: false
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"

before_install:
  - openssl aes-256-cbc -K $encrypted_036b6519a3f0_key -iv $encrypted_036b6519a3f0_iv -in TempSPC.pfx.enc -out TempSPC.pfx -d
  - openssl aes-256-cbc -K $encrypted_ee46f54e7cdc_key -iv $encrypted_ee46f54e7cdc_iv -in Certificates.p12.enc -out Certificates.p12 -d
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && \
      curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | \
      tar -xz -C /tmp/git-lfs --strip-components 1

      export PATH="/tmp/git-lfs:$PATH"
    else
      docker pull electronuserland/builder:wine
    fi

before_script:
  - git lfs pull
  - export APP_VERSION=1.0.`git log --oneline | wc -l | tr -d ' '`
  - echo $APP_VERSION
  - npm --allow-same-version --no-git-tag-version version $APP_VERSION

script:
  - env | grep -iE 'DEBUG|NODE_|ELECTRON_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_' > /tmp/env
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file /tmp/env \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm install; npm run dist-win"
    else
      npm run dist-mac
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_deploy:
  - git tag v$APP_VERSION
  - ls
  - ls dist
  - echo $CSC_LINK
  - echo $CSC_KEY_PASSWORD

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BnGBLy4uvbiWmjbO1mbm8QSDH7z8GJ+HoDwtZn2V9dvH8LUpAJDtyYisx234khQjy5AL6l80tC3Hlf9h3Am6I0MCovBrR7rmrPmuHVyeE64qGzqCiN5lDxdsvLfrqOuaZghdGBQTBZ3eIgBoGl+PErWIay4YY8lC7b9AcDwW3Tvc6GihlwfPyknhBDJecWaI4CLP0pCMOG40U6K/XPcV/PLQwupQi657GQtcMH/IM9i4WASg9cMPgO5u9LnGS4cVO8NhAz9Wp0+QOO81OnYn4X1lgDnGPRNVlTPkWWVNqHFlL1ElCPJjoII7dtQaJKaOXybh70l9uNecRly/1ot6Po2QrP1DythBwtwXbUaysU+BNcAiy6MOwQuV3jD9Qt8kmADKIvERK2B/5VNsEWurD1KDit9myunFbzRdeDDyqfmJ4ArN9zrPbBtxGgtDmQo0deYWX/UjBqwmNfO1GLoSdvil1fGAx9QK39PwxUaEbcJ9WKJke37jX/1WHdDKJuaNWc/fukjYaZNeE15b/5yc7WtUYwWC11GOvtGNjCF+IwV3lRgZy6vDK2kJ9AgI1OAkIQQ50LP9HXpEZJRwFStcN6S9wVYhwpL5V9yfW6l86DYnTrLxRRUvvk5BrBBRMfP18jvzpotd11r8Hom8yoiBnknEpJlMzBazAsEkFELmQmo=
  file_glob: true
  file: dist/*.{exe,dmg}
env:
  global:
  # - ELECTRON_CACHE=$HOME/.cache/electron
  # - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  # - _CSC_LINK=TempSPC.pfx
  - CSC_LINK=Certificates.p12
  - secure: "PATIGN4vVIBGyrR59PZBPreV95EOc8rpsFbQxwz61avgpbW+bNZBrQ8MUZS3Wv7psFrRR4r0whOWiglQ8rercTE1UPfW4+hrxpaLVJjnjbrre8uHiCU7dgDaa1cXYZSGM0BDy2BJ4nQZg9QYZL6m4QI4btOTMWh0H9vlMKaDl/3y3w8WGn2Y9mvoruNZBdX0EnBaRNnKSEw3/TP9DOt/cwUuFG3tTxHV2hgK6m3/NC6nJDxEszd0Faf6YftyiVHUWvOK6h5wT5N6jpGM5BLPvb217MwmH8sWk3nQCF3aX6y6Frxarb6hsS/cHcRzhoB04CNu0a4TFDvX9pOTEElY4OuGGU0r9gF/zelIjFEkBFdap4/33IBqYELXNe8MCawb0eFbao0VZf5jWIFuciJVVJIJf+EtiSvAruxMU3rD5duJxBDpdg0oLy7n0X/6iKTjU/Btj2KPmOgv/vziyc7/iBNO+aX0L3CBERaImXwumsVXsf9sx49M+yFFvYwBLQyizraLZa2vVGoviPpHSZ3u3t758ACUwJaBbKMNaleeyTz9ybgf/uvmdG8F5hSW8DG99mNIb2pxQFC+hGqLkfAXYyVkKcrFMyM2iGViPuWaD5/+75GvSjbo9OlApxfSncCqDIFqrRGeE8cIBqN7LoIMMopQubyYBtbkueCSSX2Hqjc="
  # - CSC_KEY_PASSWORD=test
  # - secure: tS6L7J+Rr01atE+TFEDJpmXvWCxgOnKXgsyM11KvzCYFI6c3adKzIlfS2l2jHhK270bTsvcsFpVN77KExs/IKPejQ+oVTp2WRl7yHYrD9T1RqV74vQA2ZtRKs927hnac/UCMVNwAiw15LCgmPWJn6HEdAf/4LwIUGRU95IZlvJdbfFGQr9o1eOMuy/PtSXE+Et1aLDY09uGdnChFV8TTuVRpV7In5/NooE6VZoWCP1y2Qvw0evggFXR/y7MNcjV2B+MiEyxlG9i8ihR5zITWvzylO9EHauFfCXzA0M6gX0nroyOahZn0oIRLsQfJtjlIc9B/oI+9WwLTjNWF4oiAu5K0iOHXSd8C29jrkpgscg/O21EavohNHHRBn+ObhsfvsvQk3j3IhVGh4FIL6/ATY57qR8ym3fXyNtOO1eafVc0LzhjSqyVFEpvJBlAvjCIbJPjL/G+ifBbUU+/XH6zLZu8iyGBBKx9K+m++FM/zDHrAS9eLYb+KNHACytu6VwgxlSEv32x2JWC+mWVyMjRD1c4HO0MD+rkchigqEOlO6rwPkD6aK5NkIr8eRaJIODh5xVaSOHrIhrfI/r6NYfXXEs6G4Ikt/998hl4wTnc81P6KUNnd0ayHYzzv3i6jpDBd9s35mThe1QDqg8Q1kYMKURIzehAZere0ssm9KVe45BY=
